apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  namespace: kafka
spec:
  type: LoadBalancer
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
